// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task2.API.Data;

#nullable disable

namespace Task2.API.Migrations
{
    [DbContext(typeof(UniversityContext))]
    partial class UniversityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Task2.API.Data.Models.Assignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<string>("AssignmentTitle")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("MaxGrade")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("AssignmentId")
                        .HasName("PK__Assignme__32499E77F66859D5");

                    b.HasIndex("CourseId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("Task2.API.Data.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("CommentContent")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedeByUserId")
                        .HasColumnType("int");

                    b.HasKey("CommentId")
                        .HasName("PK__Comments__C3B4DFCA5E277882");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("CreatedeByUserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Task2.API.Data.Models.Courser", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("StarteDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("SyllabusId")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("CourseId")
                        .HasName("PK__Coursers__C92D71877F3C3C3A");

                    b.HasIndex("SyllabusId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Coursers");
                });

            modelBuilder.Entity("Task2.API.Data.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<int?>("Grade1")
                        .HasColumnType("int")
                        .HasColumnName("Grade");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("GradeId")
                        .HasName("PK__Grades__54F87A5783E53AE4");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("Task2.API.Data.Models.Syllabus", b =>
                {
                    b.Property<int>("SyllabusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SyllabusId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("SyllabusId")
                        .HasName("PK__Syllabus__9B8016A6BC42B6D4");

                    b.ToTable("Syllabus", (string)null);
                });

            modelBuilder.Entity("Task2.API.Data.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "EmailAddress" }, "EmailAddress_Users_unique")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Task2.API.Data.Models.Assignment", b =>
                {
                    b.HasOne("Task2.API.Data.Models.Courser", "Course")
                        .WithMany("Assignments")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_Assignments_Coursers");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Task2.API.Data.Models.Comment", b =>
                {
                    b.HasOne("Task2.API.Data.Models.Assignment", "Assignment")
                        .WithMany("Comments")
                        .HasForeignKey("AssignmentId")
                        .IsRequired()
                        .HasConstraintName("FK__Comments__Assign__412EB0B6");

                    b.HasOne("Task2.API.Data.Models.User", "CreatedeByUser")
                        .WithMany("Comments")
                        .HasForeignKey("CreatedeByUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Comments__Create__4222D4EF");

                    b.Navigation("Assignment");

                    b.Navigation("CreatedeByUser");
                });

            modelBuilder.Entity("Task2.API.Data.Models.Courser", b =>
                {
                    b.HasOne("Task2.API.Data.Models.Syllabus", "Syllabus")
                        .WithMany("Coursers")
                        .HasForeignKey("SyllabusId")
                        .HasConstraintName("FK_Coursers_Syllabus");

                    b.HasOne("Task2.API.Data.Models.User", "Teacher")
                        .WithMany("Coursers")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK_Coursers_Users");

                    b.Navigation("Syllabus");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Task2.API.Data.Models.Grade", b =>
                {
                    b.HasOne("Task2.API.Data.Models.Assignment", "Assignment")
                        .WithMany("Grades")
                        .HasForeignKey("AssignmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Grades_Assignments");

                    b.HasOne("Task2.API.Data.Models.User", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Grades_Users");

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Task2.API.Data.Models.Assignment", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("Task2.API.Data.Models.Courser", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Task2.API.Data.Models.Syllabus", b =>
                {
                    b.Navigation("Coursers");
                });

            modelBuilder.Entity("Task2.API.Data.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Coursers");

                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
